### ISSUE TITLE
Seeking ReadableStream

### ISSUE THREAD

**Issue by ThEditor** [Tenpi/soundcloud.ts#29]
So I was trying to implement this with [discordjs v12's voice](https://github.com/discordjs/discord.js/blob/v12/src/client/voice/player/BasePlayer.js) and i tried to seek the track. It did not end up seeking the song for some reason and stopped playing the track but i worked around it using [miniget](https://www.npmjs.com/package/miniget) instead of [axios](https://www.npmjs.com/package/axios), maybe you can take a further look in this.
Workaround code:
```typerscript
import miniget from 'miniget';
private downloadTrackReadableStream = async (songUrl: string): Promise<NodeJS.ReadableStream> => {
        const url = await this.streamLink(songUrl);
        const readable = miniget(url);
        return readable;
}
```

**Comment by Tenpi** [comment]
Playing a `ReadableStream` with discord.js is buggy in general, which is why I recommend downloading it and playing an audio file instead. However, if changing the dependency to `miniget` really resolves the issue for you, then open a pull request which replaces all instances of `axios` with `miniget`, and I'll happily merge it.

**Comment by ThEditor** [comment]
`miniget` can't replace the `axios` as a whole since it's only a http(s) GET library though

**Comment by Tenpi** [comment]
> `miniget` can't replace `axios` as a whole since it's only a http(s) GET library though

There is a `post` method, but it is currently unused. It could be deleted.

However, I would prefer using a library that does more than http GET since there could be endpoints that use POST in the future. Have you tried other http libraries such as `node-fetch`, `got`, and `superagent`? My understanding is that this problem is exclusive to how `axios` handles streams.

**Comment by ThEditor** [comment]
Tried out `node-fetch` and it does seem to work too. So i guess that proves the problem to be exclusive to `axios`. I'll try to make a pull request soon.

**Comment by Tenpi** [comment]
Closing as inactive if you still have trouble with `axios` i'd forward the bug over to them and just update the package over here
