### ISSUE TITLE
Issue with streaming certain tracks

### ISSUE THREAD

**Issue by GeorgeKandamkolathy** [Tenpi/soundcloud.ts#36]
Streaming certain tracks triggers an error
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received null

Traced the error to Util.js line 114 where a url is set for an axios call.
Haven't been able to figure out why certain tracks cause this issue and not others. 
One track with this issue : https://soundcloud.com/nirvana/smells-like-teen-spirit-1

Thank you

**Comment by Tenpi** [comment]
Some tracks doesn't have a full mp3 stream, only a collection of mp3 "chunks". To get the full track you need to collect all those chunks and concat them together. 

Thus it will not be possible to stream those tracks in memory because in order to concat them (using something like ffmpeg), I will have to write them to the filesystem. However, I may add support for downloading these tracks.

**Comment by Tenpi** [comment]
I added support for downloading the mp3 chunks, requires having ffmpeg installed. I write to file system but delete it after.
